# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MJUjwoAqrw8wtCkfmxygmvG0b2fjgW-i
"""

import pandas as pd
import numpy as np
import sklearn
from sklearn import linear_model
from sklearn.utils import shuffle

"""We loaded our neccessary libraries

Now its time to load our dataset
"""

data = pd.read_csv('student-mat.csv',sep=';')

"""Trim our dataset and choose our desired columns"""

data = data[["G1", "G2", "G3", "studytime", "failures", "absences"]]

"""Let's See a piece of dataset"""

print(data.head())

"""Assume that we want to predict G# based on the others"""

predict = "G3"

X = np.array(data.drop([predict], 1)) # Features
y = np.array(data[predict]) # Labels

"""After this we need to split our data into testing and training data. We will use 90% of our data to train and the other 10% to test. The reason we do this is so that we do not test our model on data that it has already seen."""

x_train, x_test, y_train, y_test = sklearn.model_selection.train_test_split(X, y, test_size = 0.1)

"""defining the model which we will be using."""

linear = linear_model.LinearRegression()

"""train and score our model using the arrays we created before"""

linear.fit(x_train, y_train)
acc = linear.score(x_test, y_test) # acc stands for accuracy

"""To see how well our algorithm performed on our test data we can print out the accuracy."""

print(acc)

"""If we want to see the constants used to generate the line we can type the following."""

print('Coefficient: \n', linear.coef_) # These are each slope value
print('Intercept: \n', linear.intercept_) # This is the intercept

"""we are going to print out all of our test data. Beside this data we will print the actual final grade and our models predicted grade."""

predictions = linear.predict(x_test) # Gets a list of all predictions

for x in range(len(predictions)):
    print(predictions[x], x_test[x], y_test[x])